# Generated by Django 3.2.23 on 2023-11-16 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20231115_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_customers',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
